### ISSUE TITLE
topics links should take user to a list of thinkers with the same topic

### ISSUE THREAD

**Issue by langjoh** [Powerglove/Thinkerinnen#28]

**Comment by jbrunton** [comment]
Some suggestions. Note that there are always multiple ways to achieve an end with Rails, so you might find different approaches!
1. Think about what you want the page to look like from the user's point of view. We usually want the URL to be descriptive, so for example you might have `/topics/example%20topic` take the user to a list of thinkers for 'example topic'. (Note that a space is encoded as %20, so the URL will never be perfectly human readable if we allow spaces, but this is typically good enough.)
2. You'll need a new controller action for this page. You could consider creating a separate 'topics' controller to keep concerns separated.
3. You can use the acts_as_taggable_gem to find thinkers based on the topic parameter: `Thinker.tagged_with(params[:topic])`
4. When you add a new route, you can use the `as:` option to name it so that you have helper methods to reference it by (there are examples of how to do this in the generated comments in the routes.rb file). So if you add a route named 'topic' (i.e. `as: 'topic'`), you'll have the helper method `topic_url` which you can use to generate links to the topic.
5. Don't forget to think about tests!
